server:
  port: 8787
spring:
#  main:
#    web-application-type: NONE
  server:
    datasource:
      url: jdbc:sqlite:data.db
      driverClassName: org.sqlite.JDBC
  netty: 
    agent: 
      port: 50000 #自己电脑internet代理端口
    auth: 
      host: localhost #network-server 部署的ip地址
      port: 36500 #network-server 配置的代理端口
loggin:
  config: classpath:log4j2.xml      